version: "3.4"

services:
  db:
    image: postgres
    container_name: belgium-drive-postgres
    environment:
      POSTGRES_USER: belgium-drive-user
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: belgium-drive
    ports:
      - "5433:5432"
    volumes:
      - belgium-drive-postgres-volume:/var/lib/postgresql/data
      - ./dumps:/dumps

volumes:
  belgium-drive-postgres-volume:
